### ISSUE TITLE
[Bug] Problem when deploying on Heroku

### ISSUE THREAD

**Issue by rsnivelo** [creativetimofficial/material-dashboard#125]
### Version
latest
### Reproduction link
https://dashboard.heroku.com/apps/angular-app-sample
### Operating System
Heroku Dyno
### Device
everything
### Browser & Version
all
### Steps to reproduce
I'm trying to deploy an applicationm, I have followed the steps on forums to get done, but I get this error. 

Running build
       
       > angular-app@2.4.0 build /tmp/build_b6a38948b9f869f71e3e00acfb9c4614
       > ng build
       
/tmp/build_b6a38948b9f869f71e3e00acfb9c4614/node_modules/@angular/cli/bin/ng:23
  );
  ^
SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
npm ERR! Linux 4.4.0-1073-aws
npm ERR! argv "/tmp/build_b6a38948b9f869f71e3e00acfb9c4614/.heroku/node/bin/node" "/tmp/build_b6a38948b9f869f71e3e00acfb9c4614/.heroku/node/bin/npm" "run" "build" "--if-present"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! angular-app@2.4.0 build: `ng build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-app@2.4.0 build script 'ng build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-app
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/build_b6a38948b9f869f71e3e00acfb9c4614/npm-debug.log
-----> Build failed
### What is expected?
To be deployed
### What is actually happening?
Not deployed

---

**Comment by EINazare** [comment]
Hello there, @rsnivelo ,

Please share with us a link with the product that you are using from https://creative-tim.com.

Best,
Manu

**Comment by rsnivelo** [comment]
Hi @EINazare  

Sure, this one https://demos.creative-tim.com/material-dashboard-angular2/#/dashboard

**Comment by EINazare** [comment]
Hello there, @rsnivelo ,

Unfortunately, we do not have experience with deploying Angular products to Heroku but only on Github Pages.
And for Github Pages, we've used this tutorial: https://angular.io/guide/deployment#deploy-to-github-pages
Maybe this will help you as well: https://blog.bitsrc.io/deploy-your-angular-project-to-github-pages-7cbacb96f35b

Also, please note that you have wrongfully opened this issue on the HTML product and not on the Angular one.

We will leave this issue open for now with the Help Wanted label - hoping somebody with more experience from our community will come to your help, and when we'll make our next update to this product, we'll close it.

Best,
Manu
